server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index TableGenerator.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Cache para los assets estáticos
    location ~* \.(html|css|js|svg)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}